name: Go API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Set up Go"
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: "Build Go"
      run: |
        cd api
        go build -v ./...
