name: github pages

on:
  push:
    branches:
      - master

jobs:
  dioxus-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["nightly"]
        buildMode: ["release"]
        outDirectory: ["dist"]
        rootPath: ["."]

    steps:
      - uses: actions/checkout@v4
      - name: "Checkout Repository"
        run: |
          mv ./web/* ./
          rm -rf ./web

      # - name: "Dioxus Deploy"
      #   uses: DioxusLabs/deploy-action@0.1.1
      #   with:
      #     toolchain: "nightly"
      #     rootPath: "."
      #     buildMode: "release"
      #     outDirectory: "dist"

      - name: "Set up Rust toolchain"
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - name: "Cache Rust dependencies"
        uses: Swatinem/rust-cache@v2

      - name: "Install Dioxus-CLI & Build Project 🎁"
        shell: bash
        run: |
          cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
          rustup toolchain install ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          cd ${{ matrix.rootPath }} && dx build --${{ matrix.buildMode }} && cp ./${{ matrix.outDirectory }}/index.html ./${{ matrix.outDirectory }}/404.html

      - name: "Deploy Project 🚀"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ${{ matrix.rootPath }}/${{ matrix.outDirectory }}
          clean: false
