name: github pages

on:
  push:
    branches:
      - master

jobs:
  dioxus-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Change directory"
        run: |
          mv ./web/* ./
          rm -rf ./web
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0.1.1
        with:
          toolchain: "nightly"
          rootPath: "."
          buildMode: "release"
          outDirectory: "dist"
